version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
      # - ./static:/var/www/html/static
      # - ./node_modules:/var/www/html/node_modules
    ports:
      - "8080:80"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "triam"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8081:80"
    depends_on:
      - db  
  
volumes:
  db-data: